[packaging]
package_name = "azure-mgmt-hybridkubernetes"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "Hybrid Kubernetes Management"
package_doc_id = "hybrid-kubernetes"
is_stable = false
is_arm = true
